"""empty message

Revision ID: 01469bc8941f
Revises: 015cdf18cb92
Create Date: 2025-09-04 23:05:24.527859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01469bc8941f'
down_revision = '015cdf18cb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
