"""empty message

Revision ID: 015cdf18cb92
Revises: 8c20af373ec0
Create Date: 2025-09-04 22:35:33.980798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015cdf18cb92'
down_revision = '8c20af373ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist',
    sa.Column('jti', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocklist')
    # ### end Alembic commands ###
